version: '3.6'

services:

    storm-nimbus:
        image: storm
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - "6627:6627"
            - "8000:8000"

            
    storm-cli:
        image: effeerre/storm-cli
        container_name: storm-cli
        depends_on:
            - zookeeper
            - storm-nimbus
            - redis
        links:
            - zookeeper
            - storm-nimbus
            - redis
        entrypoint: /bin/bash
        stdin_open: true
        tty: true
        volumes: 
            - ./data:/data


    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        ports:
             - "2181:2181"


    storm-ui: 
        image: storm
        container_name: storm-ui
        command: storm ui
        depends_on: 
            - storm-nimbus
            - zookeeper
        links: 
            - storm-nimbus
            - zookeeper
        restart: always
        ports:
            - "8080:8080"


    worker1:
        image: storm
        command: storm supervisor
        container_name: worker1
        depends_on:
            - storm-nimbus
            - zookeeper
            - redis
        links:
            - storm-nimbus
            - redis
            - zookeeper
        restart: always


    redis:
        image: redis:3.2-alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
 

    redis-web-ui:
        image: marian/rebrow:latest
        hostname: redis-web-ui
        container_name: redis_web_ui
        depends_on:
            - redis
        ports:
            - "5001:5001"

    